// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_on_lite_tuples
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:227403133571:web:24f046ec2432a4f40ee1b6',
    messagingSenderId: '227403133571',
    projectId: 'chat-de6a4',
    authDomain: 'chat-de6a4.firebaseapp.com',
    databaseURL: 'https://chat-de6a4-default-rtdb.firebaseio.com',
    storageBucket: 'chat-de6a4.firebasestorage.app',
    measurementId: 'G-P29RFNRJEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:227403133571:android:17c0a51c5687fa2c0ee1b6',
    messagingSenderId: '227403133571',
    projectId: 'chat-de6a4',
    databaseURL: 'https://chat-de6a4-default-rtdb.firebaseio.com',
    storageBucket: 'chat-de6a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:227403133571:ios:54b849baf26735b90ee1b6',
    messagingSenderId: '227403133571',
    projectId: 'chat-de6a4',
    databaseURL: 'https://chat-de6a4-default-rtdb.firebaseio.com',
    storageBucket: 'chat-de6a4.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSpZ-PoHvhLkgpIrJdw5l0gHsqmF920js',
    appId: '1:227403133571:ios:54b849baf26735b90ee1b6',
    messagingSenderId: '227403133571',
    projectId: 'chat-de6a4',
    databaseURL: 'https://chat-de6a4-default-rtdb.firebaseio.com',
    storageBucket: 'chat-de6a4.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0sxAm8V23Trw9DmD1IlhC8MOaigu557U',
    appId: '1:227403133571:web:a23847677addabcb0ee1b6',
    messagingSenderId: '227403133571',
    projectId: 'chat-de6a4',
    authDomain: 'chat-de6a4.firebaseapp.com',
    databaseURL: 'https://chat-de6a4-default-rtdb.firebaseio.com',
    storageBucket: 'chat-de6a4.firebasestorage.app',
    measurementId: 'G-HNDL66ZG1Y',
  );

}
